/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalproject;

import java.awt.image.BufferedImage;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class FetchAdmissionInfo extends javax.swing.JFrame {

    /**
     * Creates new form FetchAdmissionInfo
     */
    public FetchAdmissionInfo() {
        initComponents();
        setValues();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlmain = new javax.swing.JPanel();
        lblphoto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtlocal = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtpermanent = new javax.swing.JTextArea();
        lbllocmsg = new javax.swing.JLabel();
        lbllocmsg1 = new javax.swing.JLabel();
        btnnext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlmain.setBackground(new java.awt.Color(153, 153, 255));
        pnlmain.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        lblphoto.setBackground(new java.awt.Color(51, 51, 51));
        lblphoto.setOpaque(true);

        txtlocal.setEditable(false);
        txtlocal.setBackground(new java.awt.Color(51, 51, 51));
        txtlocal.setColumns(15);
        txtlocal.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtlocal.setForeground(new java.awt.Color(153, 153, 255));
        txtlocal.setRows(5);
        jScrollPane1.setViewportView(txtlocal);

        txtpermanent.setEditable(false);
        txtpermanent.setBackground(new java.awt.Color(51, 51, 51));
        txtpermanent.setColumns(15);
        txtpermanent.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtpermanent.setForeground(new java.awt.Color(153, 153, 255));
        txtpermanent.setRows(5);
        jScrollPane2.setViewportView(txtpermanent);

        lbllocmsg.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lbllocmsg.setForeground(new java.awt.Color(102, 0, 204));
        lbllocmsg.setText("Local Address");

        lbllocmsg1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lbllocmsg1.setForeground(new java.awt.Color(102, 0, 204));
        lbllocmsg1.setText("Permanent Address");

        btnnext.setBackground(new java.awt.Color(0, 0, 0));
        btnnext.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnnext.setForeground(new java.awt.Color(153, 153, 255));
        btnnext.setText("Save & Next");
        btnnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlmainLayout = new javax.swing.GroupLayout(pnlmain);
        pnlmain.setLayout(pnlmainLayout);
        pnlmainLayout.setHorizontalGroup(
            pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlmainLayout.createSequentialGroup()
                .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlmainLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlmainLayout.createSequentialGroup()
                                    .addComponent(lbllocmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(227, 227, 227)))
                            .addComponent(lbllocmsg1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlmainLayout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(btnnext, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlmainLayout.setVerticalGroup(
            pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlmainLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlmainLayout.createSequentialGroup()
                        .addComponent(lbllocmsg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbllocmsg1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblphoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addComponent(btnnext, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlmain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlmain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
        // TODO add your handling code here:
        String data[]={String.valueOf(studid)};
        SubjectChoice.main(data);
        dispose();
    }//GEN-LAST:event_btnnextActionPerformed

    
    private void setValues()
    {
        Connection con = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        
        try 
        {
            con = CommonFunctions.getCon(); // Step 1: Connect to the database
            String query = "SELECT photo, local_add, permanent_add FROM students WHERE studid=?"; // Step 2: Query to fetch the image
            pst = con.prepareStatement(query);
            
            pst.setInt(1, studid); // Replace with the appropriate student ID
            rs = pst.executeQuery(); // Step 3: Execute the query and get the ResultSet
            if (rs.next()) 
            {
                InputStream input = rs.getBinaryStream("photo"); // Step 4: Get the binary stream of the image
                BufferedImage bufferedImage = ImageIO.read(input);    // Convert the InputStream to a BufferedImage
                if (bufferedImage != null) 
                {
                    lblphoto.setIcon(new ImageIcon(bufferedImage));   // Convert the BufferedImage to an ImageIcon and set it to the JLabel
                } 
                else 
                {
                    JOptionPane.showMessageDialog(this,"Failed to load image from database.");
                }
                
                txtlocal.setText(rs.getString("local_add"));
                txtpermanent.setText(rs.getString("permanent_add"));
                
                input.close();   // Close the InputStream
            } 
            else 
            {
                JOptionPane.showMessageDialog(this,"No record found with the given ID.");
            }

            rs.close();
            pst.close();
            con.close();
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(this,"Error "+e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FetchAdmissionInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FetchAdmissionInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FetchAdmissionInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FetchAdmissionInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        studid=Integer.parseInt(args[0]);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FetchAdmissionInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnnext;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbllocmsg;
    private javax.swing.JLabel lbllocmsg1;
    private javax.swing.JLabel lblphoto;
    private javax.swing.JPanel pnlmain;
    private javax.swing.JTextArea txtlocal;
    private javax.swing.JTextArea txtpermanent;
    // End of variables declaration//GEN-END:variables
    private static int studid;
}
