/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalproject;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class FetchData extends javax.swing.JFrame {

    /**
     * Creates new form FetchData
     */
    public FetchData() {
        initComponents();
        lblfetch.setText("Enter "+msglbl);
        fetchValuesDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbggen = new javax.swing.ButtonGroup();
        pnldata = new javax.swing.JPanel();
        lblfetch = new javax.swing.JLabel();
        txtphn_id = new javax.swing.JTextField();
        btnback = new javax.swing.JButton();
        btnfetch = new javax.swing.JButton();
        txtfname = new javax.swing.JTextField();
        lblmsg = new javax.swing.JLabel();
        txtmname = new javax.swing.JTextField();
        txtlname = new javax.swing.JTextField();
        txtphn = new javax.swing.JTextField();
        txtmail = new javax.swing.JTextField();
        lblgen = new javax.swing.JLabel();
        chkml = new javax.swing.JRadioButton();
        chkfml = new javax.swing.JRadioButton();
        chkoth = new javax.swing.JRadioButton();
        txtstudid = new javax.swing.JTextField();
        cmbhome = new javax.swing.JComboBox<>();
        cmbclg = new javax.swing.JComboBox<>();
        btnsavenext = new javax.swing.JButton();
        datechooser = new com.toedter.calendar.JDateChooser();
        lblbdate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnldata.setBackground(new java.awt.Color(153, 153, 255));
        pnldata.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        pnldata.setPreferredSize(new java.awt.Dimension(630, 480));

        lblfetch.setBackground(new java.awt.Color(153, 153, 255));
        lblfetch.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblfetch.setForeground(new java.awt.Color(102, 0, 204));
        lblfetch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblfetch.setOpaque(true);

        txtphn_id.setBackground(new java.awt.Color(51, 51, 51));
        txtphn_id.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtphn_id.setForeground(new java.awt.Color(153, 153, 255));
        txtphn_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtphn_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtphn_idKeyTyped(evt);
            }
        });

        btnback.setBackground(new java.awt.Color(0, 0, 0));
        btnback.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnback.setForeground(new java.awt.Color(153, 153, 255));
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        btnfetch.setBackground(new java.awt.Color(0, 0, 0));
        btnfetch.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnfetch.setForeground(new java.awt.Color(153, 153, 255));
        btnfetch.setText("Fetch Data");
        btnfetch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfetchActionPerformed(evt);
            }
        });

        txtfname.setEditable(false);
        txtfname.setBackground(new java.awt.Color(51, 51, 51));
        txtfname.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtfname.setForeground(new java.awt.Color(153, 153, 255));
        txtfname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfname.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 255), 3, true), "First Name", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 0, 255))); // NOI18N

        lblmsg.setBackground(new java.awt.Color(153, 153, 255));
        lblmsg.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblmsg.setForeground(new java.awt.Color(102, 0, 204));
        lblmsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblmsg.setText("Student Information");
        lblmsg.setOpaque(true);

        txtmname.setEditable(false);
        txtmname.setBackground(new java.awt.Color(51, 51, 51));
        txtmname.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtmname.setForeground(new java.awt.Color(153, 153, 255));
        txtmname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtmname.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 255), 3, true), "Middle Name", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 0, 255))); // NOI18N

        txtlname.setEditable(false);
        txtlname.setBackground(new java.awt.Color(51, 51, 51));
        txtlname.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtlname.setForeground(new java.awt.Color(153, 153, 255));
        txtlname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtlname.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 255), 3, true), "Last Name", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 0, 255))); // NOI18N

        txtphn.setEditable(false);
        txtphn.setBackground(new java.awt.Color(51, 51, 51));
        txtphn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtphn.setForeground(new java.awt.Color(153, 153, 255));
        txtphn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtphn.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 255), 3, true), "Phone Number", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 0, 255))); // NOI18N

        txtmail.setEditable(false);
        txtmail.setBackground(new java.awt.Color(51, 51, 51));
        txtmail.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtmail.setForeground(new java.awt.Color(153, 153, 255));
        txtmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtmail.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 255), 3, true), "Email Id", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 0, 255))); // NOI18N

        lblgen.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblgen.setForeground(new java.awt.Color(102, 0, 204));
        lblgen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblgen.setText("Gender");

        cbggen.add(chkml);
        chkml.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        chkml.setForeground(new java.awt.Color(51, 51, 51));
        chkml.setText("    Male");

        cbggen.add(chkfml);
        chkfml.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        chkfml.setForeground(new java.awt.Color(51, 51, 51));
        chkfml.setText("    Female");

        cbggen.add(chkoth);
        chkoth.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        chkoth.setForeground(new java.awt.Color(51, 51, 51));
        chkoth.setText("    Other");

        txtstudid.setEditable(false);
        txtstudid.setBackground(new java.awt.Color(51, 51, 51));
        txtstudid.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtstudid.setForeground(new java.awt.Color(153, 153, 255));
        txtstudid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtstudid.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 255), 3, true), "Student Id", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 0, 255))); // NOI18N

        cmbhome.setBackground(new java.awt.Color(0, 0, 0));
        cmbhome.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        cmbhome.setForeground(new java.awt.Color(204, 204, 204));
        cmbhome.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Hometown" }));

        cmbclg.setBackground(new java.awt.Color(0, 0, 0));
        cmbclg.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        cmbclg.setForeground(new java.awt.Color(204, 204, 204));
        cmbclg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select College Name" }));

        btnsavenext.setBackground(new java.awt.Color(0, 0, 0));
        btnsavenext.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnsavenext.setForeground(new java.awt.Color(153, 153, 255));
        btnsavenext.setText("Save & Next");
        btnsavenext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsavenextActionPerformed(evt);
            }
        });

        datechooser.setBackground(new java.awt.Color(51, 51, 51));
        datechooser.setForeground(new java.awt.Color(153, 153, 255));
        datechooser.setDateFormatString("yyyy-MM-dd");
        datechooser.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        datechooser.setOpaque(false);

        lblbdate.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblbdate.setForeground(new java.awt.Color(102, 0, 204));
        lblbdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblbdate.setText("Birthdate");

        javax.swing.GroupLayout pnldataLayout = new javax.swing.GroupLayout(pnldata);
        pnldata.setLayout(pnldataLayout);
        pnldataLayout.setHorizontalGroup(
            pnldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldataLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnldataLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143))
                    .addGroup(pnldataLayout.createSequentialGroup()
                        .addGroup(pnldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnldataLayout.createSequentialGroup()
                                .addComponent(btnsavenext, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(116, 116, 116)
                                .addComponent(btnback))
                            .addGroup(pnldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnldataLayout.createSequentialGroup()
                                    .addComponent(txtstudid, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbhome, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnldataLayout.createSequentialGroup()
                                    .addComponent(lblfetch, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtphn_id, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnfetch))
                                .addGroup(pnldataLayout.createSequentialGroup()
                                    .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtmname, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(47, 47, 47)
                                    .addComponent(txtlname, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cmbclg, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnldataLayout.createSequentialGroup()
                                    .addGroup(pnldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(datechooser, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(pnldataLayout.createSequentialGroup()
                                            .addGap(32, 32, 32)
                                            .addComponent(lblbdate, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(pnldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnldataLayout.createSequentialGroup()
                                            .addComponent(lblgen, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(83, 83, 83))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnldataLayout.createSequentialGroup()
                                            .addComponent(chkml)
                                            .addGap(12, 12, 12)
                                            .addComponent(chkfml)
                                            .addGap(12, 12, 12)
                                            .addComponent(chkoth))))
                                .addGroup(pnldataLayout.createSequentialGroup()
                                    .addComponent(txtphn, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(47, 47, 47)
                                    .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 22, Short.MAX_VALUE))))
        );
        pnldataLayout.setVerticalGroup(
            pnldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldataLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnldataLayout.createSequentialGroup()
                        .addGroup(pnldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblfetch, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtphn_id, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnfetch))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtlname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtphn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblgen, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblbdate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(chkml)
                                .addComponent(chkfml)
                                .addComponent(chkoth))
                            .addComponent(datechooser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(txtstudid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbhome, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbclg, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnback)
                    .addComponent(btnsavenext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnldata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnldata, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtphn_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtphn_idKeyTyped
        // TODO add your handling code here:
        if(Character.isDigit(evt.getKeyChar()))
        {
            int len=txtphn_id.getText().length();
            if(msglbl.contains("Phone") && len==10)
            {
                evt.consume();
            }
            else if(msglbl.contains("Id") && len>4)
            {
                evt.consume();
            }
        }
        else
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtphn_idKeyTyped

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        New_Old.main(null);
        dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnfetchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfetchActionPerformed
        // TODO add your handling code here:
        Connection con;
        PreparedStatement pst;
        ResultSet rs,rshome,rsclg;
        String query,queryhome,queryclg;
        try
        {
            con=CommonFunctions.getCon();
            if(msglbl.contains("Id"))
            {
                query="select studid,fname,mname,lname,phn_no,email,birth_date,hometown_id,gender,college_id from students where studid=?";
                pst=con.prepareStatement(query);
                pst.setInt(1, Integer.parseInt(txtphn_id.getText()));
            }
            else
            {
                query="select studid,fname,mname,lname,phn_no,email,birth_date,hometown_id,gender,college_id from students where phn_no=?";
                pst=con.prepareStatement(query);
                pst.setString(1, txtphn_id.getText());
            }
            rs=pst.executeQuery();
            if(rs.next())
            {
                txtstudid.setText(String.valueOf(rs.getInt("studid")));
                txtfname.setText(rs.getString("fname"));
                if(rs.getString("mname")==null && rs.getString("lname")==null)
                {
                    txtmname.setText("");
                    txtlname.setText("");
                }
                else if(rs.getString("mname")==null)
                {
                    txtmname.setText("");
                }
                else if(rs.getString("lname")==null)
                {
                    txtlname.setText("");
                }
                else
                {
                    txtmname.setText(rs.getString("mname"));
                    txtlname.setText(rs.getString("lname"));
                }
                txtphn.setText(rs.getString("phn_no"));
                txtmail.setText(rs.getString("email"));
                
                Date date=rs.getDate("birth_date");
                datechooser.setDate(date);
                
                queryhome="select hometown from home_town where hometownid=?";
                pst=con.prepareStatement(queryhome);
                pst.setInt(1, rs.getInt("hometown_id"));
                rshome=pst.executeQuery();
                if(rshome.next())
                {
                    cmbhome.setSelectedItem(rshome.getString("hometown"));
                }
                
                String gen=rs.getString("gender");
                if(chkfml.getText().trim().equalsIgnoreCase(gen))
                {
                    chkfml.setSelected(true);
                }
                else if(chkml.getText().trim().equalsIgnoreCase(gen))
                {
                    chkml.setSelected(true);
                }
                else
                {
                    chkoth.setSelected(true);
                }
                
                queryclg="select clgName from college where collegeid=?";
                pst=con.prepareStatement(queryclg);
                pst.setInt(1, rs.getInt("college_id"));
                rsclg=pst.executeQuery();
                if(rsclg.next())
                {
                    cmbclg.setSelectedItem(rsclg.getString("clgName"));
                }
            }
            flag=true; //no one is allowed to move ahead unless data is filled hence flag
            pst.close();
            con.close();
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this, "Fetching Unsuccesful! ","Fetch Data",JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_btnfetchActionPerformed

    private void btnsavenextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsavenextActionPerformed
        // TODO add your handling code here:
        String data[]={txtstudid.getText()};
        if(Enquiry_Admission.isenquiry && flag)
        {
            SubjectChoice.main(data);
            dispose();
        }
        else if(flag && isPrevAdmission())
        {
            FetchAdmissionInfo.main(data);
            dispose();
        }
        else if(isPrevAdmission()==false)
        {
            GetAdmissionInfo.main(data);
            dispose();
        }
    }//GEN-LAST:event_btnsavenextActionPerformed

    private void fetchValuesDB()
    {
        Connection con;
        try 
        {
            con=CommonFunctions.getCon();
            String query="select hometown from home_town";
            Statement st=con.createStatement();
            ResultSet rs;
            rs=st.executeQuery(query);
            while(rs.next())
            {
                cmbhome.addItem(rs.getString("hometown"));
            }
            
            query="select clgName from college";
            rs=st.executeQuery(query);
            while(rs.next())
            {
                cmbclg.addItem(rs.getString("clgName"));
            }
            st.close();
            con.close();
        } 
        catch (SQLException e) 
        {
            System.out.println("Exception Caught : "+e);
        }
    }
    
    private boolean isPrevAdmission()
    {
        Connection con;
        PreparedStatement pst;
        ResultSet rs;
        
        try
        {
            con=CommonFunctions.getCon();
            String query="select admissionid from admission where stud_id=?";
            pst=con.prepareStatement(query);
            pst.setInt(1, Integer.parseInt(txtstudid.getText()));
            rs=pst.executeQuery();
            while(rs.next())
            {
                return true;
            }
            pst.close();
            con.close();
        }
        catch(SQLException  ex)
        {
            JOptionPane.showMessageDialog(this, "Error: "+ex);
        }
        return false;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FetchData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FetchData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FetchData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FetchData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        msglbl=args[0];
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FetchData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnfetch;
    private javax.swing.JButton btnsavenext;
    private javax.swing.ButtonGroup cbggen;
    private javax.swing.JRadioButton chkfml;
    private javax.swing.JRadioButton chkml;
    private javax.swing.JRadioButton chkoth;
    private javax.swing.JComboBox<String> cmbclg;
    private javax.swing.JComboBox<String> cmbhome;
    private com.toedter.calendar.JDateChooser datechooser;
    private javax.swing.JLabel lblbdate;
    private javax.swing.JLabel lblfetch;
    private javax.swing.JLabel lblgen;
    private javax.swing.JLabel lblmsg;
    private javax.swing.JPanel pnldata;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtmail;
    private javax.swing.JTextField txtmname;
    private javax.swing.JTextField txtphn;
    private javax.swing.JTextField txtphn_id;
    private javax.swing.JTextField txtstudid;
    // End of variables declaration//GEN-END:variables
    private static String msglbl;
    private boolean flag=false;
}
