/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalproject;

import com.github.sarxos.webcam.Webcam;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class GetAdmissionInfo extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form GetAdmissionInfo
     */
    public GetAdmissionInfo() {
        initComponents();
        flag=true;
        webcam=Webcam.getDefault();
        webcam.open();
        t=new Thread(this);
        t.start();
    }
    
    public void run()
    {
        while(flag)
        {
            try
            {
                lblphoto.setIcon(new ImageIcon(webcam.getImage()));
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this, "Some problem with Webcam","Webcam",JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlmain = new javax.swing.JPanel();
        lblphoto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtlocal = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtpermanent = new javax.swing.JTextArea();
        lbllocmsg = new javax.swing.JLabel();
        lbllocmsg1 = new javax.swing.JLabel();
        tbtnclick = new javax.swing.JToggleButton();
        btnsave = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnnext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlmain.setBackground(new java.awt.Color(153, 153, 255));
        pnlmain.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        lblphoto.setBackground(new java.awt.Color(51, 51, 51));
        lblphoto.setOpaque(true);

        txtlocal.setBackground(new java.awt.Color(51, 51, 51));
        txtlocal.setColumns(15);
        txtlocal.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtlocal.setForeground(new java.awt.Color(153, 153, 255));
        txtlocal.setRows(5);
        jScrollPane1.setViewportView(txtlocal);

        txtpermanent.setBackground(new java.awt.Color(51, 51, 51));
        txtpermanent.setColumns(15);
        txtpermanent.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtpermanent.setForeground(new java.awt.Color(153, 153, 255));
        txtpermanent.setRows(5);
        jScrollPane2.setViewportView(txtpermanent);

        lbllocmsg.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lbllocmsg.setForeground(new java.awt.Color(102, 0, 204));
        lbllocmsg.setText("Local Address");

        lbllocmsg1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lbllocmsg1.setForeground(new java.awt.Color(102, 0, 204));
        lbllocmsg1.setText("Permanent Address");

        tbtnclick.setBackground(new java.awt.Color(0, 0, 0));
        tbtnclick.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        tbtnclick.setForeground(new java.awt.Color(153, 153, 255));
        tbtnclick.setText("Click");
        tbtnclick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnclickActionPerformed(evt);
            }
        });

        btnsave.setBackground(new java.awt.Color(0, 0, 0));
        btnsave.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnsave.setForeground(new java.awt.Color(153, 153, 255));
        btnsave.setText("Save");
        btnsave.setActionCommand("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 153, 255));
        jButton1.setText("Same as Local Address");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnnext.setBackground(new java.awt.Color(0, 0, 0));
        btnnext.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnnext.setForeground(new java.awt.Color(153, 153, 255));
        btnnext.setText("Save & Next");
        btnnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlmainLayout = new javax.swing.GroupLayout(pnlmain);
        pnlmain.setLayout(pnlmainLayout);
        pnlmainLayout.setHorizontalGroup(
            pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlmainLayout.createSequentialGroup()
                .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlmainLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlmainLayout.createSequentialGroup()
                                .addComponent(tbtnclick, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42)
                        .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlmainLayout.createSequentialGroup()
                                    .addComponent(lbllocmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(227, 227, 227)))
                            .addGroup(pnlmainLayout.createSequentialGroup()
                                .addComponent(lbllocmsg1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))))
                    .addGroup(pnlmainLayout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(btnnext, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        pnlmainLayout.setVerticalGroup(
            pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlmainLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlmainLayout.createSequentialGroup()
                        .addComponent(lbllocmsg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbllocmsg1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlmainLayout.createSequentialGroup()
                        .addComponent(lblphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbtnclick, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35)
                .addComponent(btnnext, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlmain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlmain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbtnclickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnclickActionPerformed
        // TODO add your handling code here:
        int cnt=1;
        if(tbtnclick.isSelected())
        {
            tbtnclick.setText("Try Again");
            flag=false;
            Image image=webcam.getImage();
            lblphoto.setIcon(new ImageIcon(image));
        }
        else
        {
            tbtnclick.setText("Click");
            flag=true;
            t=new Thread(this);
            t.start();
        }
    }//GEN-LAST:event_tbtnclickActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Image Saved!");
    }//GEN-LAST:event_btnsaveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txtpermanent.setText(txtlocal.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
        // TODO add your handling code here:
        
        /*try
        {
            ImageIO.write(webcam.getImage(),"JPG", new File("E:\\BVCOEW\\Java\\FinalProject\\src\\finalproject\\mypic.jpg"));
            Connection con = CommonFunctions.getCon();
            String query = "update students set photo=?,local_add=?,permanent_add=? where studid=?";
            PreparedStatement pst = con.prepareStatement(query);
            FileInputStream fis = new FileInputStream("E:\\BVCOEW\\Java\\FinalProject\\src\\finalproject\\bus1.jpg");
            pst.setBinaryStream(1, fis, fis.available());
            pst.setString(2, txtlocal.getText());
            pst.setString(3, txtpermanent.getText());
            pst.setInt(4, studid);
            pst.executeUpdate();
        }
        catch(SQLException e)
        {
            
        }
        catch(IOException ex)
        {
            JOptionPane.showMessageDialog(this, "Error : "+ex);
        }*/
        try 
        {
        // Capture the image from the label icon
            ImageIcon icon = (ImageIcon) lblphoto.getIcon();
            if (icon != null) 
            {
                Image image = icon.getImage();

                // Convert the Image to a BufferedImage
                BufferedImage bufferedImage = new BufferedImage(image.getWidth(null), image.getHeight(null), BufferedImage.TYPE_INT_RGB);
                Graphics2D g2d = bufferedImage.createGraphics();
                g2d.drawImage(image, 0, 0, null);
                g2d.dispose();

                // Convert the BufferedImage to byte array
                ByteArrayOutputStream baos = new ByteArrayOutputStream();
                ImageIO.write(bufferedImage, "jpg", baos);
                byte[] imageBytes = baos.toByteArray();

                // Establish database connection and update query
                Connection con = CommonFunctions.getCon();
                String query = "UPDATE students SET photo = ?, local_add = ?, permanent_add = ? WHERE studid = ?";
                PreparedStatement pst = con.prepareStatement(query);

                // Set the image as a binary stream
                pst.setBinaryStream(1, new ByteArrayInputStream(imageBytes), imageBytes.length);
                pst.setString(2, txtlocal.getText());
                pst.setString(3, txtpermanent.getText());
                pst.setInt(4, studid);

                // Execute the update
                int updatedRows = pst.executeUpdate();
                if (updatedRows > 0) 
                {
                    JOptionPane.showMessageDialog(this, "Image and details saved successfully!");
                    String data[] = {String.valueOf(studid)};
                    SubjectChoice.main(data);
                    dispose();
                } 
                else 
                {
                    JOptionPane.showMessageDialog(this, "No records updated!");
                }

                pst.close();
                con.close();
            } 
            else 
            {
                JOptionPane.showMessageDialog(this, "No image available to save!");
            }
        } 
        catch (SQLException e) 
        {
            JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
        } 
        catch (IOException ex) 
        {
            JOptionPane.showMessageDialog(this, "Image Processing Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnnextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GetAdmissionInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GetAdmissionInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GetAdmissionInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GetAdmissionInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        studid=Integer.parseInt(args[0]);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GetAdmissionInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnnext;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbllocmsg;
    private javax.swing.JLabel lbllocmsg1;
    private javax.swing.JLabel lblphoto;
    private javax.swing.JPanel pnlmain;
    private javax.swing.JToggleButton tbtnclick;
    private javax.swing.JTextArea txtlocal;
    private javax.swing.JTextArea txtpermanent;
    // End of variables declaration//GEN-END:variables
    private Webcam webcam;
    private Thread t;
    private volatile boolean flag;
    private static int studid;
}
