/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalproject;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class GetDataEnquiry extends javax.swing.JFrame {

    /**
     * Creates new form GetDataEnquiry
     */
    public GetDataEnquiry() {
        initComponents();
        fetchValuesDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbggen = new javax.swing.ButtonGroup();
        pnlmain = new javax.swing.JPanel();
        txtfname = new javax.swing.JTextField();
        txtmname = new javax.swing.JTextField();
        txtlname = new javax.swing.JTextField();
        lblhead = new javax.swing.JLabel();
        txtphn = new javax.swing.JTextField();
        txtmail = new javax.swing.JTextField();
        chkml = new javax.swing.JRadioButton();
        chkfml = new javax.swing.JRadioButton();
        chkoth = new javax.swing.JRadioButton();
        lblgen = new javax.swing.JLabel();
        cmbhome = new javax.swing.JComboBox<>();
        cmbclg = new javax.swing.JComboBox<>();
        btnhomeadd = new javax.swing.JButton();
        btnclgadd = new javax.swing.JButton();
        btnsavenext = new javax.swing.JButton();
        datechooser = new com.toedter.calendar.JDateChooser();
        lblbdate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlmain.setBackground(new java.awt.Color(153, 153, 255));
        pnlmain.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        txtfname.setBackground(new java.awt.Color(51, 51, 51));
        txtfname.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtfname.setForeground(new java.awt.Color(153, 153, 255));
        txtfname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfname.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 255), 3, true), "First Name", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 0, 255))); // NOI18N
        txtfname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfnameKeyTyped(evt);
            }
        });

        txtmname.setBackground(new java.awt.Color(51, 51, 51));
        txtmname.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtmname.setForeground(new java.awt.Color(153, 153, 255));
        txtmname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtmname.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 255), 3, true), "Middle Name", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 0, 255))); // NOI18N
        txtmname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmnameKeyTyped(evt);
            }
        });

        txtlname.setBackground(new java.awt.Color(51, 51, 51));
        txtlname.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtlname.setForeground(new java.awt.Color(153, 153, 255));
        txtlname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtlname.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 255), 3, true), "Last Name", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 0, 255))); // NOI18N
        txtlname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtlnameKeyTyped(evt);
            }
        });

        lblhead.setFont(new java.awt.Font("Segoe UI Semibold", 3, 24)); // NOI18N
        lblhead.setForeground(new java.awt.Color(102, 0, 204));
        lblhead.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblhead.setText("Fill Student Information");

        txtphn.setBackground(new java.awt.Color(51, 51, 51));
        txtphn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtphn.setForeground(new java.awt.Color(153, 153, 255));
        txtphn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtphn.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 255), 3, true), "Phone Number", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 0, 255))); // NOI18N
        txtphn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtphnKeyTyped(evt);
            }
        });

        txtmail.setBackground(new java.awt.Color(51, 51, 51));
        txtmail.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtmail.setForeground(new java.awt.Color(153, 153, 255));
        txtmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtmail.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 255), 3, true), "Email Id", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 0, 255))); // NOI18N

        cbggen.add(chkml);
        chkml.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        chkml.setForeground(new java.awt.Color(51, 51, 51));
        chkml.setText("    Male");

        cbggen.add(chkfml);
        chkfml.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        chkfml.setForeground(new java.awt.Color(51, 51, 51));
        chkfml.setText("    Female");

        cbggen.add(chkoth);
        chkoth.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        chkoth.setForeground(new java.awt.Color(51, 51, 51));
        chkoth.setText("    Other");

        lblgen.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblgen.setForeground(new java.awt.Color(102, 0, 204));
        lblgen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblgen.setText("Gender");

        cmbhome.setBackground(new java.awt.Color(0, 0, 0));
        cmbhome.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        cmbhome.setForeground(new java.awt.Color(255, 255, 255));
        cmbhome.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Hometown" }));

        cmbclg.setBackground(new java.awt.Color(0, 0, 0));
        cmbclg.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        cmbclg.setForeground(new java.awt.Color(204, 204, 204));
        cmbclg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select College Name" }));

        btnhomeadd.setBackground(new java.awt.Color(0, 0, 0));
        btnhomeadd.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnhomeadd.setForeground(new java.awt.Color(153, 153, 255));
        btnhomeadd.setText("Add");
        btnhomeadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeaddActionPerformed(evt);
            }
        });

        btnclgadd.setBackground(new java.awt.Color(0, 0, 0));
        btnclgadd.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnclgadd.setForeground(new java.awt.Color(153, 153, 255));
        btnclgadd.setText("Add");
        btnclgadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclgaddActionPerformed(evt);
            }
        });

        btnsavenext.setBackground(new java.awt.Color(0, 0, 0));
        btnsavenext.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnsavenext.setForeground(new java.awt.Color(153, 153, 255));
        btnsavenext.setText("Save & Next");
        btnsavenext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsavenextActionPerformed(evt);
            }
        });

        datechooser.setBackground(new java.awt.Color(51, 51, 51));
        datechooser.setForeground(new java.awt.Color(153, 153, 255));
        datechooser.setDateFormatString("yyyy-MM-dd");
        datechooser.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        datechooser.setOpaque(false);

        lblbdate.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblbdate.setForeground(new java.awt.Color(102, 0, 204));
        lblbdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblbdate.setText("Birthdate");

        javax.swing.GroupLayout pnlmainLayout = new javax.swing.GroupLayout(pnlmain);
        pnlmain.setLayout(pnlmainLayout);
        pnlmainLayout.setHorizontalGroup(
            pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlmainLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlmainLayout.createSequentialGroup()
                        .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtphn, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlmainLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(lblbdate, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(datechooser, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlmainLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlmainLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblgen, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlmainLayout.createSequentialGroup()
                                        .addComponent(chkml)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                        .addComponent(chkfml)
                                        .addGap(16, 16, 16)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkoth))))
                    .addGroup(pnlmainLayout.createSequentialGroup()
                        .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(txtmname, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtlname, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlmainLayout.createSequentialGroup()
                        .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbclg, 0, 420, Short.MAX_VALUE)
                            .addComponent(cmbhome, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnhomeadd, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnclgadd, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlmainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblhead, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
            .addGroup(pnlmainLayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(btnsavenext, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlmainLayout.setVerticalGroup(
            pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlmainLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblhead, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtlname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtphn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblgen, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblbdate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chkml)
                        .addComponent(chkfml)
                        .addComponent(chkoth))
                    .addComponent(datechooser, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbhome, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhomeadd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbclg, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnclgadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnsavenext)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlmain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlmain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnhomeaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeaddActionPerformed
        // TODO add your handling code here:
        String hometown=JOptionPane.showInputDialog(this, "Enter hometown", "New Value", JOptionPane.QUESTION_MESSAGE);
        if(hometown!=null && hometown.length()!=0)
        {
            try 
            {
                Connection con=CommonFunctions.getCon();
                String query="insert into home_town(hometown) values(?)";
                PreparedStatement pst=con.prepareStatement(query);
                pst.setString(1, hometown);
                int cnt=pst.executeUpdate();
                if(cnt==1)
                {
                    JOptionPane.showMessageDialog(this, "Insertion Succesful!","Insertion",JOptionPane.INFORMATION_MESSAGE);
                    cmbhome.addItem(hometown);
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Insertion Unsuccesful!","Insertion",JOptionPane.ERROR_MESSAGE);
                }
                pst.close();
                con.close();
            } 
            catch (SQLException e) 
            {
                JOptionPane.showMessageDialog(this, "Insertion Unsuccesful!","Insertion",JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Insertion Unsuccesful!","Insertion",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnhomeaddActionPerformed

    private void btnclgaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclgaddActionPerformed
        // TODO add your handling code here:
        String clgname=JOptionPane.showInputDialog(this, "Enter College Name", "New Value", JOptionPane.QUESTION_MESSAGE);
        if(clgname!=null && clgname.length()!=0)
        {
            try 
            {
                Connection con=CommonFunctions.getCon();
                String query="insert into college(clgName) values(?)";
                PreparedStatement pst=con.prepareStatement(query);
                pst.setString(1, clgname);
                int cnt=pst.executeUpdate();
                if(cnt==1)
                {
                    JOptionPane.showMessageDialog(this, "Insertion Succesful!","Insertion",JOptionPane.INFORMATION_MESSAGE);
                    cmbclg.addItem(clgname);
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Insertion Unsuccesful!","Insertion",JOptionPane.ERROR_MESSAGE);
                }
                pst.close();
                con.close();
            } 
            catch (SQLException e) 
            {
                JOptionPane.showMessageDialog(this, "Insertion Unsuccesful!","Insertion",JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Insertion Unsuccesful!","Insertion",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnclgaddActionPerformed

    private void btnsavenextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsavenextActionPerformed
        // TODO add your handling code here:
        boolean flag;
        flag=displayErrors();
        Connection con;
        PreparedStatement pst;
        ResultSet rs;
        if(!flag)
        {
            try
            {
                con=CommonFunctions.getCon();
                String query;
                int hometownid=0,collegeid=0,offset;

                query="select hometownid from home_town where hometown=?";
                pst=con.prepareStatement(query);
                pst.setString(1, (String) cmbhome.getSelectedItem());
                rs=pst.executeQuery();
                if(rs.next())
                {
                    hometownid=rs.getInt("hometownid");
                }

                query="select collegeid from college where clgName=?";
                pst=con.prepareStatement(query);
                pst.setString(1, (String) cmbclg.getSelectedItem());
                rs=pst.executeQuery();
                if(rs.next())
                {
                    collegeid=rs.getInt("collegeid");
                }

                Date bd;
                bd=datechooser.getDate();
                SimpleDateFormat formatdate=new SimpleDateFormat("yyyy-MM-dd");
                String bdate=formatdate.format(bd);

                if(txtmname.getText().length()==0 && txtlname.getText().length()==0)
                {
                    query="insert into students(fname,phn_no,email,birth_date,hometown_id,gender,college_id) values(?,?,?,?,?,?,?)";
                    pst=con.prepareStatement(query);
                    offset=2;
                }
                else if(txtmname.getText().length()==0)
                {
                    query="insert into students(fname,lname,phn_no,email,birth_date,hometown_id,gender,college_id) values(?,?,?,?,?,?,?,?)";
                    pst=con.prepareStatement(query);
                    pst.setString(2, txtlname.getText());
                    offset=3;
                }
                else if(txtlname.getText().length()==0)
                {
                    query="insert into students(fname,mname,phn_no,email,birth_date,hometown_id,gender,college_id) values(?,?,?,?,?,?,?,?)";
                    pst=con.prepareStatement(query);
                    pst.setString(2, txtmname.getText());
                    offset=3;
                }
                else
                {
                    query="insert into students(fname,mname,lname,phn_no,email,birth_date,hometown_id,gender,college_id) values(?,?,?,?,?,?,?,?,?)";
                    pst=con.prepareStatement(query);
                    pst.setString(2, txtmname.getText());
                    pst.setString(3, txtlname.getText());
                    offset=4;
                }
                pst.setString(1, txtfname.getText());
                pst.setString(offset++, txtphn.getText());
                pst.setString(offset++, txtmail.getText());
                pst.setString(offset++,bdate);
                pst.setInt(offset++, hometownid);
                String gender=chkfml.isSelected()?chkfml.getActionCommand():chkml.getActionCommand();
                if(!gender.contains("F"))
                {
                    gender=chkoth.isSelected()?chkoth.getActionCommand():chkml.getActionCommand();
                }
                pst.setString(offset++, gender.trim());
                pst.setInt(offset, collegeid);

                int cnt=pst.executeUpdate();
                if(cnt==1)
                {
                    JOptionPane.showMessageDialog(this, "Student details Saved Succesfully!","Student Details",JOptionPane.INFORMATION_MESSAGE);
                    
                    query="select studid from students where phn_no=?";
                    pst=con.prepareStatement(query);
                    pst.setString(1, txtphn.getText());
                    rs=pst.executeQuery();
                    if(rs.next())
                    {
                        studid=String.valueOf(rs.getInt("studid"));
                    }

                    String data[]={studid};
                    if(Enquiry_Admission.isenquiry)
                    {
                        SubjectChoice.main(data);
                    }
                    else
                    {
                        GetAdmissionInfo.main(data);
                    }
                    dispose();
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Student Details Insertion Unsuccesful!","Enquiry Insertion",JOptionPane.ERROR_MESSAGE);
                }
                pst.close();
                con.close();
            }
            catch(SQLException e)
            {
                String errormsg=""+e;
                if(errormsg.contains("Duplicate"))
                {
                    if(errormsg.contains("phn_no"))
                    {
                        JOptionPane.showMessageDialog(this, "Student Details Insertion Unsuccesful!\nDuplicate Entry for Phone Number!","Insertion",JOptionPane.ERROR_MESSAGE);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "Student Details Insertion Unsuccesful!\nDuplicate Entry for Email Id!","Insertion",JOptionPane.ERROR_MESSAGE);
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Student Details Insertion Unsuccesful!","Insertion",JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnsavenextActionPerformed

    boolean displayErrors()
    {
         
        String regexemail = "^[A-Za-z0-9+_.-]+@(.+)$";  //Regular Expression  
        Pattern patternemail = Pattern.compile(regexemail);  //Compile regular expression to get the pattern  
        Matcher matcheremail = patternemail.matcher(txtmail.getText());  
        
        /*String regexbdate="^\\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])$";
        Pattern patternbdate = Pattern.compile(regexbdate);   
        Matcher matcherbdate = patternbdate.matcher(datechooser.getDate());*/
        
        String error="";
        int cnt=1;
        if(txtfname.getText().length()==0)
        {
            error=error+cnt+". First name cannot be blank!\n";
            cnt++;
        }
        if(txtphn.getText().length()<10)
        {
            error=error+cnt+". Phone Number is not of 10 digits!\n";
            cnt++;
        }
        if(matcheremail.matches()==false)
        {
            error=error+cnt+". Email is not in proper format!\n";
            cnt++;
        }
        if(datechooser.getDate()==null)
        {
            error=error+cnt+". Select Birthdate!\n";
            cnt++;
        }
        if(cbggen.getSelection()==null)
        {
            error=error+cnt+". Select Gender!\n";
            cnt++;
        }
        if(cmbhome.getSelectedIndex()==0)
        {
            error=error+cnt+". Select Hometown!\n";
            cnt++;
        }
        if(cmbclg.getSelectedIndex()==0)
        {
            error=error+cnt+". Select College Name!\n";
            cnt++;
        }
        if(!error.equals(""))
        {
            error=error+cnt+". Ensure Phone Number and Email are Unique!";
            JOptionPane.showMessageDialog(this,error,cnt+" Errors", JOptionPane.ERROR_MESSAGE);
            return true;
        }
        return false;
    }
    
    private void txtphnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtphnKeyTyped
        // TODO add your handling code here:
        if(Character.isDigit(evt.getKeyChar()))
        {
            int len=txtphn.getText().length();
            if(len==10)
            {
                evt.consume();
            }
        }
        else
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtphnKeyTyped

    private void txtlnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlnameKeyTyped
        // TODO add your handling code here:
        if(Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtlnameKeyTyped

    private void txtmnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmnameKeyTyped
        // TODO add your handling code here:
        if(Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtmnameKeyTyped

    private void txtfnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfnameKeyTyped
        // TODO add your handling code here:
        if(Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtfnameKeyTyped

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GetDataEnquiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GetDataEnquiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GetDataEnquiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GetDataEnquiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                /*GetDataEnquiry obj=new GetDataEnquiry();
                obj.setVisible(true);*/
                new GetDataEnquiry().setVisible(true);
            }
        });
    }
    
    private void fetchValuesDB()
    {
        Connection con;
        try 
        {
            con=CommonFunctions.getCon();
            String query="select hometown from home_town";
            Statement st=con.createStatement();
            ResultSet rs;
            rs=st.executeQuery(query);
            while(rs.next())
            {
                cmbhome.addItem(rs.getString("hometown"));
            }
            
            query="select clgName from college";
            rs=st.executeQuery(query);
            while(rs.next())
            {
                cmbclg.addItem(rs.getString("clgName"));
            }
            st.close();
            con.close();
        } 
        catch (SQLException e) 
        {
            System.out.println("Exception Caught : "+e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclgadd;
    private javax.swing.JButton btnhomeadd;
    private javax.swing.JButton btnsavenext;
    private javax.swing.ButtonGroup cbggen;
    private javax.swing.JRadioButton chkfml;
    private javax.swing.JRadioButton chkml;
    private javax.swing.JRadioButton chkoth;
    private javax.swing.JComboBox<String> cmbclg;
    private javax.swing.JComboBox<String> cmbhome;
    private com.toedter.calendar.JDateChooser datechooser;
    private javax.swing.JLabel lblbdate;
    private javax.swing.JLabel lblgen;
    private javax.swing.JLabel lblhead;
    private javax.swing.JPanel pnlmain;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtmail;
    private javax.swing.JTextField txtmname;
    private javax.swing.JTextField txtphn;
    // End of variables declaration//GEN-END:variables
    private String studid;
}
