/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalproject;

import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class New_Old extends javax.swing.JFrame {

    /**
     * Creates new form New_Old
     */
    public New_Old() {
        initComponents();
        if(!Enquiry_Admission.isenquiry)
        {
            lblmsg1.setText("If a student has made a prior enquiry,");
            lblmsg2.setText("they should be considered an old student.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbgnewold = new javax.swing.ButtonGroup();
        pnlnewold = new javax.swing.JPanel();
        lblhead = new javax.swing.JLabel();
        chknew = new javax.swing.JRadioButton();
        chkold = new javax.swing.JRadioButton();
        btnphn = new javax.swing.JButton();
        lblfetch = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();
        btnstudid = new javax.swing.JButton();
        lblor = new javax.swing.JLabel();
        lblmsg1 = new javax.swing.JLabel();
        lblmsg2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlnewold.setBackground(new java.awt.Color(153, 153, 255));
        pnlnewold.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        lblhead.setBackground(new java.awt.Color(153, 153, 255));
        lblhead.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lblhead.setForeground(new java.awt.Color(102, 0, 204));
        lblhead.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblhead.setText("Student is?");

        chknew.setBackground(new java.awt.Color(153, 153, 255));
        cbgnewold.add(chknew);
        chknew.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        chknew.setForeground(new java.awt.Color(51, 51, 51));
        chknew.setText("    New Student");
        chknew.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chknewItemStateChanged(evt);
            }
        });

        chkold.setBackground(new java.awt.Color(153, 153, 255));
        cbgnewold.add(chkold);
        chkold.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        chkold.setForeground(new java.awt.Color(51, 51, 51));
        chkold.setText("    Old Student");

        btnphn.setBackground(new java.awt.Color(0, 0, 0));
        btnphn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnphn.setForeground(new java.awt.Color(153, 153, 255));
        btnphn.setText("Phone Number");
        btnphn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnphnActionPerformed(evt);
            }
        });

        lblfetch.setBackground(new java.awt.Color(153, 153, 255));
        lblfetch.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblfetch.setForeground(new java.awt.Color(51, 51, 51));
        lblfetch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblfetch.setText("Fetch Student Data Using?");

        btnback.setBackground(new java.awt.Color(0, 0, 0));
        btnback.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnback.setForeground(new java.awt.Color(153, 153, 255));
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        btnstudid.setBackground(new java.awt.Color(0, 0, 0));
        btnstudid.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnstudid.setForeground(new java.awt.Color(153, 153, 255));
        btnstudid.setText("Student Id");
        btnstudid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstudidActionPerformed(evt);
            }
        });

        lblor.setBackground(new java.awt.Color(153, 153, 255));
        lblor.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblor.setForeground(new java.awt.Color(51, 51, 51));
        lblor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblor.setText("OR");

        lblmsg1.setBackground(new java.awt.Color(153, 153, 255));
        lblmsg1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblmsg1.setForeground(new java.awt.Color(102, 0, 204));
        lblmsg1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblmsg1.setText(" ");
        lblmsg1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblmsg1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblmsg2.setBackground(new java.awt.Color(153, 153, 255));
        lblmsg2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblmsg2.setForeground(new java.awt.Color(102, 0, 204));
        lblmsg2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblmsg2.setText(" ");
        lblmsg2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblmsg2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlnewoldLayout = new javax.swing.GroupLayout(pnlnewold);
        pnlnewold.setLayout(pnlnewoldLayout);
        pnlnewoldLayout.setHorizontalGroup(
            pnlnewoldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlnewoldLayout.createSequentialGroup()
                .addGroup(pnlnewoldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlnewoldLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblfetch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlnewoldLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(lblhead, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlnewoldLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnphn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblor, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnstudid, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlnewoldLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlnewoldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlnewoldLayout.createSequentialGroup()
                        .addGroup(pnlnewoldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkold, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chknew, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlnewoldLayout.createSequentialGroup()
                        .addComponent(btnback)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlnewoldLayout.createSequentialGroup()
                        .addGroup(pnlnewoldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblmsg2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblmsg1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))))
        );
        pnlnewoldLayout.setVerticalGroup(
            pnlnewoldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlnewoldLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblhead, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(lblmsg1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblmsg2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(chknew)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkold)
                .addGap(24, 24, 24)
                .addComponent(lblfetch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlnewoldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnphn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnstudid, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblor, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(btnback)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlnewold, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlnewold, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnphnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnphnActionPerformed
        // TODO add your handling code here:
        if(cbgnewold.getSelection()!=null)
        {
            String data[]={"Phone Number"};
            FetchData.main(data);
            dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(this,"\'Old\' is not selected!\nSelect \'Old\' to fetch data\n using Phone Number","Select Old", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnphnActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        Enquiry_Admission.main(null);
        dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void chknewItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chknewItemStateChanged
        // TODO add your handling code here:
        GetDataEnquiry.main(null);
        dispose();
    }//GEN-LAST:event_chknewItemStateChanged

    private void btnstudidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstudidActionPerformed
        // TODO add your handling code here:
        if(cbgnewold.getSelection()!=null)
        {
            String data[]={"Student Id"};
            FetchData.main(data);
            dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(this,"\'Old\' is not selected!\nSelect \'Old\' to fetch data\n using Student Id","Select Old", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnstudidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New_Old.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New_Old.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New_Old.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New_Old.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new New_Old().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnphn;
    private javax.swing.JButton btnstudid;
    private javax.swing.ButtonGroup cbgnewold;
    private javax.swing.JRadioButton chknew;
    private javax.swing.JRadioButton chkold;
    private javax.swing.JLabel lblfetch;
    private javax.swing.JLabel lblhead;
    private javax.swing.JLabel lblmsg1;
    private javax.swing.JLabel lblmsg2;
    private javax.swing.JLabel lblor;
    private javax.swing.JPanel pnlnewold;
    // End of variables declaration//GEN-END:variables
}
