/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalproject;


import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class SubjectChoice extends javax.swing.JFrame {

    /**
     * Creates new form SubjectChoice
     */
    public SubjectChoice() {
        initComponents();
        dbFetchSubNames();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlsub = new javax.swing.JPanel();
        lblsub = new javax.swing.JLabel();
        cmbsuboff = new javax.swing.JComboBox<>();
        lblsuboff = new javax.swing.JLabel();
        lblfees = new javax.swing.JLabel();
        lbldur = new javax.swing.JLabel();
        txtfees = new javax.swing.JTextField();
        txtdur = new javax.swing.JTextField();
        btnaddsub = new javax.swing.JButton();
        btnupdsub = new javax.swing.JButton();
        btnsavedata = new javax.swing.JButton();
        txtaddsub = new javax.swing.JTextField();
        lbladdmsg = new javax.swing.JLabel();
        txtaddfees = new javax.swing.JTextField();
        txtadddur = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlsub.setBackground(new java.awt.Color(153, 153, 255));
        pnlsub.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        lblsub.setBackground(new java.awt.Color(153, 153, 255));
        lblsub.setFont(new java.awt.Font("Segoe UI Semibold", 3, 24)); // NOI18N
        lblsub.setForeground(new java.awt.Color(102, 0, 204));
        lblsub.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblsub.setText("Subject Offered");

        cmbsuboff.setBackground(new java.awt.Color(0, 0, 0));
        cmbsuboff.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        cmbsuboff.setForeground(new java.awt.Color(204, 204, 204));
        cmbsuboff.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbsuboffItemStateChanged(evt);
            }
        });

        lblsuboff.setBackground(new java.awt.Color(153, 153, 255));
        lblsuboff.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        lblsuboff.setForeground(new java.awt.Color(102, 0, 204));
        lblsuboff.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblsuboff.setText("Subjects");

        lblfees.setBackground(new java.awt.Color(153, 153, 255));
        lblfees.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        lblfees.setForeground(new java.awt.Color(102, 0, 204));
        lblfees.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblfees.setText("Fees");

        lbldur.setBackground(new java.awt.Color(153, 153, 255));
        lbldur.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        lbldur.setForeground(new java.awt.Color(102, 0, 204));
        lbldur.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldur.setText("Duration");

        txtfees.setEditable(false);
        txtfees.setBackground(new java.awt.Color(102, 102, 102));
        txtfees.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtfees.setForeground(new java.awt.Color(0, 0, 0));
        txtfees.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtdur.setEditable(false);
        txtdur.setBackground(new java.awt.Color(102, 102, 102));
        txtdur.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtdur.setForeground(new java.awt.Color(0, 0, 0));
        txtdur.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnaddsub.setBackground(new java.awt.Color(0, 0, 0));
        btnaddsub.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnaddsub.setForeground(new java.awt.Color(153, 153, 255));
        btnaddsub.setText("Add");
        btnaddsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddsubActionPerformed(evt);
            }
        });

        btnupdsub.setBackground(new java.awt.Color(0, 0, 0));
        btnupdsub.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnupdsub.setForeground(new java.awt.Color(153, 153, 255));
        btnupdsub.setText("Update");
        btnupdsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdsubActionPerformed(evt);
            }
        });

        btnsavedata.setBackground(new java.awt.Color(0, 0, 0));
        btnsavedata.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnsavedata.setForeground(new java.awt.Color(153, 153, 255));
        btnsavedata.setText("Save Data");
        btnsavedata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsavedataActionPerformed(evt);
            }
        });

        txtaddsub.setBackground(new java.awt.Color(51, 51, 51));
        txtaddsub.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtaddsub.setForeground(new java.awt.Color(153, 153, 255));
        txtaddsub.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtaddsub.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 51, 255), 3, true), "Subject", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 51, 255))); // NOI18N

        lbladdmsg.setBackground(new java.awt.Color(153, 153, 255));
        lbladdmsg.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lbladdmsg.setForeground(new java.awt.Color(102, 0, 204));
        lbladdmsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbladdmsg.setText("Fill Below Fields To Insert/Update Subject");

        txtaddfees.setBackground(new java.awt.Color(51, 51, 51));
        txtaddfees.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtaddfees.setForeground(new java.awt.Color(153, 153, 255));
        txtaddfees.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtaddfees.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 255), 3, true), "Fees", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 51, 255))); // NOI18N
        txtaddfees.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtaddfeesKeyTyped(evt);
            }
        });

        txtadddur.setBackground(new java.awt.Color(51, 51, 51));
        txtadddur.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtadddur.setForeground(new java.awt.Color(153, 153, 255));
        txtadddur.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtadddur.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 51, 255), 3, true), "Duration", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 51, 255))); // NOI18N
        txtadddur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtadddurKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pnlsubLayout = new javax.swing.GroupLayout(pnlsub);
        pnlsub.setLayout(pnlsubLayout);
        pnlsubLayout.setHorizontalGroup(
            pnlsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlsubLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnsavedata, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
            .addGroup(pnlsubLayout.createSequentialGroup()
                .addGroup(pnlsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlsubLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(lblsub, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlsubLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(pnlsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbladdmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlsubLayout.createSequentialGroup()
                                .addGroup(pnlsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbsuboff, 0, 135, Short.MAX_VALUE)
                                    .addComponent(lblsuboff, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                    .addComponent(txtaddsub))
                                .addGroup(pnlsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnlsubLayout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addGroup(pnlsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtfees, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                            .addComponent(lblfees, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(33, 33, 33)
                                        .addGroup(pnlsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbldur, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtdur, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlsubLayout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(txtaddfees, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtadddur, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(pnlsubLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(btnaddsub, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnupdsub, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        pnlsubLayout.setVerticalGroup(
            pnlsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlsubLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblsub, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(pnlsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsuboff, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblfees, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldur, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbsuboff, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(txtfees)
                    .addComponent(txtdur))
                .addGap(18, 18, 18)
                .addComponent(lbladdmsg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(pnlsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtaddsub)
                    .addComponent(txtadddur)
                    .addComponent(txtaddfees))
                .addGap(18, 18, 18)
                .addGroup(pnlsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnaddsub, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnupdsub, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(btnsavedata)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlsub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlsub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnsavedataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsavedataActionPerformed
        // TODO add your handling code here:
        /*check if stud id is added in the table then give the dialog box of data added successfully
        else give data insertion unsuccessfully with an error as message type dialog box*/
        if(Enquiry_Admission.isenquiry)
        {
            Connection con;
            try 
            {
                con=CommonFunctions.getCon();
                String query="insert into enquiries(stud_id,sub_Name,enquiryDate) values(?,?,?)";
                PreparedStatement pst=con.prepareStatement(query);
                pst.setInt(1, studid);//int int curdate string
                pst.setString(2, (String) cmbsuboff.getSelectedItem());
                
                SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");  
                Date date = new Date();  
                pst.setString(3,formatter.format(date));
                
                int cnt=pst.executeUpdate();
                if(cnt==1)
                {
                    JOptionPane.showMessageDialog(this, "Enquiry added Succesfully!","Enquiry Insertion",JOptionPane.INFORMATION_MESSAGE);
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Enquiry addition Unsuccesful!","Enquiry Insertion",JOptionPane.ERROR_MESSAGE);
                }
                pst.close();
                con.close();
            }
            catch (SQLException e) 
            {
                JOptionPane.showMessageDialog(this, "Enquiry addition Unsuccesful!","Enquiry Insertion",JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        {
            Connection con;
            try 
            {
                con=CommonFunctions.getCon();
                String query="insert into admission(stud_id,sub_Name,admissionDate) values(?,?,?)";
                PreparedStatement pst=con.prepareStatement(query);
                pst.setInt(1, studid);
                pst.setString(2, (String) cmbsuboff.getSelectedItem());
                
                SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");  
                Date date = new Date();  
                pst.setString(3,formatter.format(date));
                
                int cnt=pst.executeUpdate();
                if(cnt==1)
                {
                    JOptionPane.showMessageDialog(this, "Admission Succesful!","Admission",JOptionPane.INFORMATION_MESSAGE);
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Admission Unsuccesful!","Admission",JOptionPane.ERROR_MESSAGE);
                }
                pst.close();
                con.close();
            }
            catch (SQLException e) 
            {
                JOptionPane.showMessageDialog(this, "Admission Unsuccesful!","Admission",JOptionPane.ERROR_MESSAGE);
            }
        }
        dispose();
    }//GEN-LAST:event_btnsavedataActionPerformed

    private void cmbsuboffItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbsuboffItemStateChanged
        // TODO add your handling code here:
        changeSubDisplayedValues();
    }//GEN-LAST:event_cmbsuboffItemStateChanged

    private void btnaddsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddsubActionPerformed
        // TODO add your handling code here:
        if(txtaddsub.getText().length()==0 || txtaddfees.getText().length()==0 || txtadddur.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this, "Insertion Unsuccesful!\nSubject or Fees or Duration\nfields can't be empty!","Insertion",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            Connection con;
            try 
            {
                con=CommonFunctions.getCon();
                String query="insert into Subjects values(?,?,?)";
                PreparedStatement pst=con.prepareStatement(query);
                pst.setString(1, txtaddsub.getText());
                pst.setInt(2, Integer.parseInt(txtaddfees.getText()));
                pst.setInt(3, Integer.parseInt(txtadddur.getText()));
                int cnt=pst.executeUpdate();
                if(cnt==1)
                {
                    JOptionPane.showMessageDialog(this, "Insertion Succesful!","Insertion",JOptionPane.INFORMATION_MESSAGE);
                    cmbsuboff.addItem(txtaddsub.getText());
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Insertion Unsuccesful!","Insertion",JOptionPane.ERROR_MESSAGE);
                }
                pst.close();
                con.close();
            }
            catch (SQLException e) 
            {
                JOptionPane.showMessageDialog(this, "Insertion Unsuccesful!","Insertion",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnaddsubActionPerformed

    private void btnupdsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdsubActionPerformed
        // TODO add your handling code here:
        Connection con;
        try 
        {
            con=CommonFunctions.getCon();
            PreparedStatement pst;
            if(txtaddfees.getText().length()==0)
            {
                String query="update Subjects set subDuration=? where subName=?";
                pst=con.prepareStatement(query);
                pst.setInt(1, Integer.parseInt(txtadddur.getText()));
                pst.setString(2, txtaddsub.getText());
            }
            else if(txtadddur.getText().length()==0)
            {
                String query="update Subjects set subFees=? where subName=?";
                pst=con.prepareStatement(query);
                pst.setInt(1, Integer.parseInt(txtaddfees.getText()));
                pst.setString(2, txtaddsub.getText());
            }
            else
            {
                String query="update Subjects set subFees=?, subDuration=? where subName=?";
                pst=con.prepareStatement(query);
                pst.setInt(1, Integer.parseInt(txtaddfees.getText()));
                pst.setInt(2, Integer.parseInt(txtadddur.getText()));
                pst.setString(3, txtaddsub.getText());
            }
            int cnt=pst.executeUpdate();
            if(cnt==1)
            {
                JOptionPane.showMessageDialog(this, "Updated Succesfully!","Update",JOptionPane.INFORMATION_MESSAGE);
                changeSubDisplayedValues();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Update Unsuccesful!\nCheck if subject field has a value.","Update",JOptionPane.ERROR_MESSAGE);
            }
            pst.close();
            con.close();
        }
        catch (SQLException e) 
        {
            JOptionPane.showMessageDialog(this, "Update Unsuccesful!","Update",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnupdsubActionPerformed

    private void txtaddfeesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaddfeesKeyTyped
        // TODO add your handling code here:
        if(Character.isDigit(evt.getKeyChar())==false)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtaddfeesKeyTyped

    private void txtadddurKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtadddurKeyTyped
        // TODO add your handling code here:
        if(Character.isDigit(evt.getKeyChar())==false)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtadddurKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubjectChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubjectChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubjectChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubjectChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        studid=Integer.parseInt(args[0]);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubjectChoice().setVisible(true);
            }
        });
    }
    
    private void dbFetchSubNames()
    {
        Connection con;
        try
        {
            con=CommonFunctions.getCon();
            String query="select subName from Subjects";
            Statement st = con.createStatement();
            ResultSet rs;
            rs=st.executeQuery(query);
            while(rs.next())
            {
                cmbsuboff.addItem(rs.getString("subName"));
            }
            st.close();
            con.close();
        } 
        catch (SQLException ex) 
        {
            System.out.println("Exception Caught "+ex);
        }
    }
    private void changeSubDisplayedValues()
    {
        Connection con;
        try
        {
            con=CommonFunctions.getCon();
            String query="select subFees,subDuration from Subjects where subName=?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, (String) cmbsuboff.getSelectedItem());
            ResultSet rs;
            rs=pst.executeQuery();
            if(rs.next())
            {
                txtfees.setText(rs.getString("subFees"));
                txtdur.setText(rs.getString("subDuration"));
            }
            pst.close();
            con.close();
        } 
        catch (SQLException ex) 
        {
            System.out.println("Exception Caught "+ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddsub;
    private javax.swing.JButton btnsavedata;
    private javax.swing.JButton btnupdsub;
    private javax.swing.JComboBox<String> cmbsuboff;
    private javax.swing.JLabel lbladdmsg;
    private javax.swing.JLabel lbldur;
    private javax.swing.JLabel lblfees;
    private javax.swing.JLabel lblsub;
    private javax.swing.JLabel lblsuboff;
    private javax.swing.JPanel pnlsub;
    private javax.swing.JTextField txtadddur;
    private javax.swing.JTextField txtaddfees;
    private javax.swing.JTextField txtaddsub;
    private javax.swing.JTextField txtdur;
    private javax.swing.JTextField txtfees;
    // End of variables declaration//GEN-END:variables
    private static int studid;
}
